

#mysqlconfiguration
spring.datasource.url=jdbc:postgresql://dpg-d6rpmbqa214c73bkk9og-a.virginia-postgres.render.com:5432/moneymanager_nj15
spring.datasource.username=moneymanager_nj15_user
spring.datasource.password=e1bD3cQPs2fGbg0xEzUTgGMTzsl96GrC
app.activation.url=${MONEY_MANAGER_BACKEND_URL:http://localhost:8080}